// Code generated by Slice Machine. DO NOT EDIT.

import About from "./About/index.svelte";
import Contact from "./Contact/index.svelte";
import Introduction from "./Introduction/index.svelte";
import ProjectsPreview from "./ProjectsPreview/index.svelte";

export const components = {
  about: About,
  contact: Contact,
  introduction: Introduction,
  projects_preview: ProjectsPreview,
};
