// Code generated by Slice Machine. DO NOT EDIT.

import About from "./About/index.svelte";
import Introduction from "./Introduction/index.svelte";

export const components = {
  about: About,
  introduction: Introduction,
};
