// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | ContactSlice
  | ProjectsPreviewSlice
  | AboutSlice
  | IntroductionSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *About → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * title field in *About → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: about.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *About → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: I started making websites because I wanted to share my hobbies online...
   * - **API ID Path**: about.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *Contact → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * title field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in touch
   * - **API ID Path**: contact.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If you are interested in collaborating, please don't hesitate to reach out to me...
   * - **API ID Path**: contact.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Introduction → Primary*
 */
export interface IntroductionSliceDefaultPrimary {
  /**
   * title_start field in *Introduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hi, I am
   * - **API ID Path**: introduction.primary.title_start
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_start: prismic.KeyTextField;

  /**
   * title_name field in *Introduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: John Doe
   * - **API ID Path**: introduction.primary.title_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_name: prismic.KeyTextField;

  /**
   * title_end field in *Introduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: , a frontend design developer based in the Netherlands
   * - **API ID Path**: introduction.primary.title_end
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_end: prismic.KeyTextField;
}

/**
 * Default variation for Introduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroductionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Introduction*
 */
type IntroductionSliceVariation = IntroductionSliceDefault;

/**
 * Introduction Shared Slice
 *
 * - **API ID**: `introduction`
 * - **Description**: Introduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSlice = prismic.SharedSlice<
  "introduction",
  IntroductionSliceVariation
>;

/**
 * Primary content in *ProjectsPreview → Primary*
 */
export interface ProjectsPreviewSliceDefaultPrimary {
  /**
   * title field in *ProjectsPreview → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Projects
   * - **API ID Path**: projects_preview.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *ProjectsPreview → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: These are my recent projects...
   * - **API ID Path**: projects_preview.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * project field in *ProjectsPreview → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_preview.primary.project
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project: prismic.ImageField<never>;

  /**
   * project_link field in *ProjectsPreview → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_preview.primary.project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;
}

/**
 * Default variation for ProjectsPreview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsPreviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsPreviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectsPreview*
 */
type ProjectsPreviewSliceVariation = ProjectsPreviewSliceDefault;

/**
 * ProjectsPreview Shared Slice
 *
 * - **API ID**: `projects_preview`
 * - **Description**: ProjectsPreview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsPreviewSlice = prismic.SharedSlice<
  "projects_preview",
  ProjectsPreviewSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      IntroductionSlice,
      IntroductionSliceDefaultPrimary,
      IntroductionSliceVariation,
      IntroductionSliceDefault,
      ProjectsPreviewSlice,
      ProjectsPreviewSliceDefaultPrimary,
      ProjectsPreviewSliceVariation,
      ProjectsPreviewSliceDefault,
    };
  }
}
